### ISSUE TITLE
Serious errors in implementing 

### ISSUE THREAD

**Issue by peter-gribanov** [klaussilveira/SimpleSHM#3]
Expanding SHMOP intended to two different PHP process had the opportunity to work with a common memory unit. Your library does not offer such opportunities. Simple tests show that.

The new process must be able to read data from the memory unit that could be filled by another process, or may not be filled. 
```php
$memory = new Block(123);
$this->assertEmpty($memory->read());
```

Example transmitting data from one process to another.
```php
$memory = new Block(123);
$memory->write('foo');
unset($memory);

// new object
$memory = new Block(123);
$this->assertEquals('foo', $memory->read());
```

**Comment by cfilippe** [comment]
In your example:
$memory = new Block(123);
$memory->write('foo');
unset($memory);

// new object
$memory = new Block(123);
$this->assertEquals('foo', $memory->read());

The unset($memory) will imply a call to the destructor
an he removes the shared_memory segment.

If you remove the destructor from the code, it shall work.
But you'll have to invent a cleaning method to replace the removal.

**Comment by peter-gribanov** [comment]
@cfilippe you are wrong.
Shmop_close function does not remove the memory segment. To erase function is used shmop_delete.

In this task, I'm not talking about the problem of removing the data. I talking the problem of data transfer to another php process in the case of [generation the unique ID](https://github.com/klaussilveira/SimpleSHM/blob/master/src/Simple/SHM/Block.php#L43) of the block.

```php
$memory = new Block();
$memory->write('foo');
```
in a another php process trying to get the variable
```php
$memory = new Block();
$this->assertEquals('foo', $memory->read());
```
We get an error because in the first and the second case are generated different ID. Transmission of data in such cases, perform fail. So, i talking that ID does not have to be generated, and always needs to be fixed.
